# -*- coding: utf-8 -*-
"""CrewAI_Multiagent_GeminiAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjlmd5VoqvjQUIzBjLScFz4zyzBB_2DO
"""

!nvidia-smi

# !pip install crewai

# !pip install 'crewai[tools]'

# !pip install gradio

import os
from crewai import Agent, Task, Crew
from crewai_tools import SerperDevTool

os.environ['GEMINI_API_KEY'] = 'Use Api key'
os.environ['SERPER_API_KEY'] = 'use api key'

search_tool = SerperDevTool()

teacher = Agent(role ='Teacher',
                goal = 'Explain concepts clearly step by step',
                backstory = 'Expereienced teacher who explain with example',
                llm = 'gemini-2.5-flash',
                verbose = True
                )
researcher = Agent(role = 'Researcher',
                   goal = 'Find latest information',
                   backstory = 'Expert in searching real-world data',
                   tools = [search_tool],
                   llm = 'gemini-2.5-flash',
                   verbose = True
                   )
simplifier = Agent(role = 'Simplifier',
                   goal = 'Make thing easy',
                   backstory = 'Breaks complex ideas into simple language',
                   llm = 'gemini-2.5-flash',
                   verbose = True
                   )
student = Agent(role = 'Student',
                goal = 'Take notes',
                backstory = 'Writes simple notes like learner',
                llm = 'gemini-2.5-flash',
                verbose = True
                )
examiner = Agent(role = 'Examiner',
                 goal = 'Create questions',
                 backstory = 'Tests understanding',
                 llm = 'gemini-2.5-flash',
                 verbose = True
                 )
topic = 'What is difference between agents vs agentic ai vs mcp vs generative ai'

task1 = Task(
    description = f'Explain{topic} in simple steps with example',
    expected_output= 'step-by-step explanation',
    agent = teacher
)
task2 = Task(
    description = f'search and find 3 important points about {topic}',
    expected_output= '3 clear points',
    agent = researcher
)
task3 = Task(
    description = f'Simlify the explanation of {topic}',
    expected_output= 'Very simple explanation',
    agent = simplifier
)
task4 = Task(
    description = f'Write a short notes on {topic} like a student',
    expected_output= 'Simple notes',
    agent = student
)
task5 = Task(
    description = f'Create 5 questions about {topic}',
    expected_output= '3 easy questions',
    agent = examiner
)

crew = Crew(
    agents=[teacher, simplifier, student, examiner],
    tasks=[task1, task2, task3, task4, task5],
    verbose=True
)

result = crew.kickoff()

print(result)

# use Gradio
import os
import gradio as gr
from crewai import Agent, Task, Crew
from crewai_tools import SerperDevTool

os.environ['GEMINI_API_KEY'] = 'use api key'
os.environ['SERPER_API_KEY'] = 'use api key'

search_tool = SerperDevTool()

def run_multi_agent(topic):
  teacher = Agent(role ='Teacher',
                goal ='Explain concepts clearly step by step',
                backstory = 'Experienced teacher who explain with example',
                llm = 'gemini-2.5-flash',
                verbose = True)
  researcher = Agent(role = 'Researcher',
                   goal='Find latest information',
                   backstory = 'Expert in searching real-world data',
                   tools=[search_tool],
                   llm = 'gemini-2.5-flash',
                   verbose = True)
  simplifier = Agent(role = 'Simplifier',
                   goal = 'Make thing easy',
                   backstory = 'Breaks complex ideas into simple language',
                   llm = 'gemini-2.5-flash',
                   verbose=True)
  student = Agent(role= 'Student',
                goal = 'Take notes',
                backstory = 'Writes simple notes like learner',
                llm = 'gemini-2.5-flash',
                verbose = True)
  examiner = Agent (role = 'Examiner',
                 goal= 'Create questions',
                 backstory = 'Tests understanding',
                 llm = 'gemini-2.5-flash',
                 verbose=True)

  task1 = Task(
    description = f'Explain{topic} in simple steps with examples',
    expected_output= 'step-by-step explanation',
    agent = teacher)

  task2 = Task(
    description = f'search and find 3 important points about {topic}',
    expected_output = '3 clear points',
    agent = researcher)

  task3 = Task(
    description = f'Simplify the explanation of {topic}',
    expected_output='Very simple explanation',
    agent = simplifier )

  task4 = Task(
    description=f'Write short notes on {topic} like a student',
    expected_output='Simple notes',
    agent= student)

  task5 = Task(
    description=f'Create 5 questions about {topic}',
    expected_output='3 easy questions',
    agent=examiner)

  crew = Crew(
      agents=[teacher, researcher, simplifier, student, examiner],
      tasks=[task1, task2, task3, task4, task5],
      verbose=False)

  result = crew.kickoff()

  return str(result)

interface = gr.Interface(
    fn = run_multi_agent,
    inputs = gr.Textbox(
        label = 'Enter Topic',
        placeholder = 'what is Agentic AI vs single '),
    outputs = gr.Textbox(label = 'Multi-Agent Output'),
    title = 'Pallavi Khadse MultiAgent AI Training',
    description = 'Enter any topic and see multiple AI agents colabotate to teach, simplify and test you'

)

if __name__ == '__main__':
  interface.launch()